name: 'Glo Add Label To Cards'
description: 'GitHub action to add a label to Glo Boards cards'
branding:
  color: 'blue'
  icon: 'tag'
inputs:
  authToken:
    description: Auth token for user
    required: true
  cards:
    description: Array of { cardId, boardId } objects
    required: true
  label:
    description: Name of label to add to cards
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
